# Generated by Django 4.1.7 on 2023-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hron', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
