# Generated by Django 4.0.4 on 2022-10-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truba',
            name='virezka_to',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='zavar_to',
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='kol_trub_fact',
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='numb_razresh',
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='razresh',
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид деффекта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='dlina',
            field=models.FloatField(null=True, verbose_name='Длина трубы'),
        ),
        migrations.AddField(
            model_name='truba',
            name='type_remont_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод ремонта'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='file_prikaz',
            field=models.FileField(null=True, upload_to='', verbose_name='prikaz/'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='file_razresh',
            field=models.FileField(null=True, upload_to='', verbose_name='razreshenie/'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='kol_trub_fakt',
            field=models.IntegerField(null=True, verbose_name='Кол. труб по факту'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='prikaz_date',
            field=models.DateField(null=True, verbose_name='Дата совместного приказа'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='prikaz_number',
            field=models.CharField(max_length=100, null=True, verbose_name='№ совместного приказа'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='razresh_date',
            field=models.DateField(null=True, verbose_name='Дата разрешения'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='razresh_number',
            field=models.CharField(max_length=100, null=True, verbose_name='№ разрешения'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_end_fact',
            field=models.DateField(null=True, verbose_name='Дата окончания по факту'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_end_plan',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_end_razresh',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_start_fact',
            field=models.DateField(null=True, verbose_name='Дата начала по факту'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_start_plan',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='date_start_razresh',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='end_uch',
            field=models.FloatField(null=True, verbose_name='Конец участка'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='kol_trub_plan',
            field=models.IntegerField(null=True, verbose_name='Кол. труб по плану'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='lpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.lpumg', verbose_name='Наименование филиала ЛПУМГ'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='nitka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.gazopr', verbose_name='Наименование газопровода'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='start_uch',
            field=models.FloatField(null=True, verbose_name='Начало участка'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='status_uch',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус участка'),
        ),
    ]
