# Generated by Django 4.1.7 on 2023-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_hron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svarshov',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Хронические заболевания'),
        ),
    ]
