# Generated by Django 4.0.4 on 2022-12-15 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_remove_truba_virezka_to_remove_truba_zavar_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svarshov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tehnika',
            old_name='icon_name',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='truba',
            old_name='def_km_1',
            new_name='def_1_km',
        ),
        migrations.RenameField(
            model_name='truba',
            old_name='def_piket_1',
            new_name='def_1_piket',
        ),
        migrations.RenameField(
            model_name='truba',
            old_name='type_remont_1',
            new_name='def_1_type_rem',
        ),
        migrations.RenameField(
            model_name='truba',
            old_name='def_km_2',
            new_name='def_2_km',
        ),
        migrations.RenameField(
            model_name='truba',
            old_name='def_piket_2',
            new_name='def_2_piket',
        ),
        migrations.RemoveField(
            model_name='tehnika',
            name='name',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='def_km_3',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='def_percent_1',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='def_percent_2',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='def_percent_3',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='def_piket_3',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='izolirovano',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='snyato_izol',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='virezka_kat',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='vskrito',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='zasipano',
        ),
        migrations.RemoveField(
            model_name='truba',
            name='zavar_stik',
        ),
        migrations.AddField(
            model_name='tehnika',
            name='model',
            field=models.CharField(max_length=255, null=True, verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='rashod',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='teh_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резервное поле'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='teh_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резервное поле'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='teh_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резервное поле'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='teh_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резервное поле'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='teh_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резервное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='comment_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='truba',
            name='comment_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='truba',
            name='comment_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='truba',
            name='construkciya',
            field=models.CharField(max_length=50, null=True, verbose_name='Конструкция трубы'),
        ),
        migrations.AddField(
            model_name='truba',
            name='danger',
            field=models.CharField(max_length=50, null=True, verbose_name='Опасность'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_compl_rem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_10',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_4',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_5',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_6',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_7',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_8',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_dop_9',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_1_percent',
            field=models.IntegerField(null=True, verbose_name='Процент дефекта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид деффекта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_compl_rem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод ремонта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_10',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_4',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_5',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_6',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_7',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_8',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_dop_9',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное поле'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_percent',
            field=models.IntegerField(null=True, verbose_name='Процент дефекта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='def_2_type_rem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод ремонта'),
        ),
        migrations.AddField(
            model_name='truba',
            name='int_psh',
            field=models.CharField(max_length=100, null=True, verbose_name='Входящий ПШ'),
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod',
            field=models.BooleanField(default=True, verbose_name='Отвод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod_izgib',
            field=models.FloatField(null=True, verbose_name='Угол изгиба в Град.'),
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod_napravleniye',
            field=models.CharField(max_length=100, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod_proekciya',
            field=models.CharField(max_length=100, null=True, verbose_name='Угол в проекции Град.'),
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod_segment',
            field=models.IntegerField(null=True, verbose_name='Число сегментов отвода'),
        ),
        migrations.AddField(
            model_name='truba',
            name='otvod_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип отвода'),
        ),
        migrations.AddField(
            model_name='truba',
            name='out_psh',
            field=models.CharField(max_length=100, null=True, verbose_name='Исходящий ПШ'),
        ),
        migrations.AddField(
            model_name='truba',
            name='stage_works',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этап работ'),
        ),
        migrations.AddField(
            model_name='truba',
            name='stenka',
            field=models.FloatField(null=True, verbose_name='Толщина стенки'),
        ),
        migrations.AddField(
            model_name='truba',
            name='tehnika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.tehnika', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='truba',
            name='uch_trubid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='distant_location',
            field=models.BooleanField(default=True, verbose_name='Отдаленный участок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tehnika',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип техники'),
        ),
    ]
