# Generated by Django 4.0.4 on 2022-12-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_svarshov_rename_icon_name_tehnika_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Этап работ')),
            ],
        ),
        migrations.AlterField(
            model_name='truba',
            name='stage_works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.status', verbose_name='Этап работ'),
        ),
    ]
