# Generated by Django 4.0.4 on 2022-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_status_alter_truba_stage_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tehnika',
            options={'ordering': ['type', 'model', 'gos_number', 'status', 'location', 'rashod'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техники'},
        ),
        migrations.AddField(
            model_name='tehnika',
            name='location_sity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='tehnika',
            name='location',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
    ]
