# Generated by Django 4.1.7 on 2023-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_alter_hron_hron_alter_svarshov_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SZZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssz', models.CharField(blank=True, max_length=255, null=True, verbose_name='999')),
            ],
        ),
    ]
