# Generated by Django 4.1.7 on 2023-03-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_szz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SZZ',
        ),
        migrations.AddField(
            model_name='personal',
            name='hron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.hron', verbose_name='Хронические заболевания'),
        ),
    ]
