# Generated by Django 4.1.7 on 2023-04-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_truba_trump_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truba',
            old_name='trump_url',
            new_name='slug',
        ),
    ]
