# Generated by Django 4.1.7 on 2023-04-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_rename_trump_url_truba_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truba',
            old_name='slug',
            new_name='trump_url',
        ),
    ]
