# Generated by Django 4.0.4 on 2023-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0009_alter_truba_comment_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tehnika',
            options={'ordering': ['type', 'model', 'gos_number', 'status', 'location1', 'location2', 'rashod_h', 'rashod_km'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.RemoveField(
            model_name='tehnika',
            name='rashod',
        ),
        migrations.AddField(
            model_name='personal',
            name='location_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение 1'),
        ),
        migrations.AddField(
            model_name='personal',
            name='location_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение 2'),
        ),
        migrations.AddField(
            model_name='personal',
            name='ssz',
            field=models.BooleanField(default=False, verbose_name='ССЗ'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='inv_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инв.номер'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='prinadlejnost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Принадлежность'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='rashod_h',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход ч.'),
        ),
        migrations.AddField(
            model_name='tehnika',
            name='rashod_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход км.'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='davleniye',
            field=models.BooleanField(default=False, verbose_name='Участок сниженного давления'),
        ),
        migrations.AddField(
            model_name='uchastok',
            name='dlina_uchastka',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина участка'),
        ),
        migrations.AlterField(
            model_name='tehnika',
            name='location2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Труба'),
        ),
    ]
