# Generated by Django 4.1.7 on 2023-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0010_alter_tehnika_options_remove_tehnika_rashod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='next_examen_eb',
            field=models.DateField(blank=True, null=True, verbose_name='Проверка знаний по ЭБ'),
        ),
        migrations.AddField(
            model_name='personal',
            name='next_examen_ot',
            field=models.DateField(blank=True, null=True, verbose_name='Проверка знаний по ОТ'),
        ),
        migrations.AddField(
            model_name='personal',
            name='next_examen_pdd',
            field=models.DateField(blank=True, null=True, verbose_name='ПДД'),
        ),
        migrations.AddField(
            model_name='personal',
            name='next_examen_ptm',
            field=models.DateField(blank=True, null=True, verbose_name='ПТМ'),
        ),
    ]
