# Generated by Django 4.1.7 on 2023-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0011_personal_next_examen_eb_personal_next_examen_ot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='otpusk_d1',
            new_name='otpusk_d1_end',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='otpusk_d2',
            new_name='otpusk_d1_sart',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='otpusk',
            new_name='otpusk_end',
        ),
        migrations.AddField(
            model_name='personal',
            name='otpusk_d2_end',
            field=models.DateField(blank=True, null=True, verbose_name='Доп.отпуск'),
        ),
        migrations.AddField(
            model_name='personal',
            name='otpusk_d2_start',
            field=models.DateField(blank=True, null=True, verbose_name='Доп.отпуск'),
        ),
        migrations.AddField(
            model_name='personal',
            name='otpusk_start',
            field=models.DateField(blank=True, null=True, verbose_name='Осн.отпуск'),
        ),
    ]
